# name: deploy-client

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'client/**'
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: cd client && docker build -t haoxiang310/client .
#       - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       - run: docker push haoxiang310/client
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{secrets. DIGITALOCEAN_ACCESS_TOKEN}}
#       - run: doctl kubernetes cluster kubeconfig save 18576ef5-b358-4919-8675-5c3ea22dc22c
#       - run: kubectl rollout restart deployment client-depl
